name: Proxy Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # اجرا هر 30 دقیقه یک بار

jobs:
  run-proxy-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Proxy Scraper
        env:
          API_ID: ${{ secrets.AP
