name: Run Telegram Proxy Bot

on:
  push:
    branches:
      - main  # این خط تعیین می‌کند که فقط وقتی به شاخه اصلی (main) push می‌شود، workflow اجرا شود.

jobs:
  run_bot:
    runs-on: ubuntu-latest  # سیستم عامل Ubuntu برای اجرا
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # این خط کد را از مخزن شما دریافت می‌کند.

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # نسخه پایتونی که می‌خواهید استفاده کنید.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # نصب کتابخانه‌های مورد نیاز از فایل requirements.txt

      - name: Run Telegram Bot Script
        run: |
          python proxy_bot.py  # اجرای اسکریپت پایتون شما
